plugins {
    id 'com.android.application'
}

android {
    namespace 'com.agushermawan.portofolio'
    compileSdk 34

    defaultConfig {
        applicationId "com.agushermawan.portofolio"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "2.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

configurations.all {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}
